#!/usr/bin/env zsh

emulate -R zsh
setopt extendedglob typesetsilent warncreateglobal noshortloops rcquotes

typeset -g name=$1
typeset -ga reply full_names
typeset -g URL="https://api.github.com/search/repositories?q=$name+in:name+fork:false"

#typeset -g CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/z-a-unscope"
#command mkdir -p "$CACHE_DIR"

download() {
    local url=$URL"+$1&sort=stars&order=desc"
    reply=( "${(@f)"$(curl --silent -i "$url")"}" )
}

integer forks

for forks ( 10 2 0 ) {
    download "forks:>=$forks"
    full_names=( ${(M)reply[@]:#[[:space:]]#\"full_name\":[[:space:]]#*,} )
    full_names=( "${${(M)full_names[@]//(#b)[[:space:]]#\"full_name\":[[:space:]]#\"(*)\",/${match[1]}}[@]}" )
    full_names=( ${(M)full_names[@]:#*/$name} )
    if (( ${#full_names} )) {
        print -r -- $forks: $full_names[1]
        exit 0
    }
}

exit 1
